### ISSUE TITLE
IP150 with firmware version < 4 connection stability

### ISSUE THREAD

**Issue by yozik04** [jpbarraca/pai#12]
Connection stability to IP150 module is pretty bad.
IP module closes socket if interface is idle. I see winload constantly requests something, so the connection does not time out. I can't find any keep alive requests.
I have added some reconnection logic. But after long run and many disconnects IP module connects but panel does not respond anymore.

WinLoad out (disconnected) is sent after 4 seconds of inactivity.
Socket is still connected and receives events.
Socket times out after 60 seconds of inactivity.

**Comment by yozik04** [comment]
When socket times out USER LED turns OFF.

After many disconnects when I got lock up USER LED was ON and stayed ON after many minutes.

**Comment by yozik04** [comment]
@jpbarraca Where did you get spec for IP module? Maybe there is a keep alive request? Or you did Struct from the tcpdump?

**Comment by iondarie** [comment]
He got the dumps from my IP150 v4 and my friends v1.39.

Unfortunately he does not own a IP150 module

As always if anything is needed from my ip150 i can provide teamviewer for babyware to my ip150

**Comment by jpbarraca** [comment]
We must poll the module constantly. Otherwise it will disconnect us. There was a bug related to the events: if wee kept receiving an event every second (e.g., zone open), the receiving logic (send_wait), would never stop handling events, and we would be disconnected.

I made some changes to try to avoid this in my last commits. Could this be related?

When connecting through STUN, the session needs to be refreshed every 10 minutes.

**Comment by yozik04** [comment]
#18 Fixes it.
